

services:
  # Offer Scraper Demo Server (serves ACP documents)
  offer-scraper:
    build:
      context: ./apps/offer-scraper
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    networks:
      - acp-network
    profiles:
      - setup

  # Global Offer Registry (GOR) API
  gor-api:
    build:
      context: ./apps/gor-api
      dockerfile: Dockerfile
    container_name: acp-gor-api
    ports:
      - "3001:3001"
    env_file:
      - ./apps/gor-api/.env
    environment:
      - PYTHONPATH=/app/src
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - DEMO_SERVER_URL=http://host.docker.internal:3000
    volumes:
      - ./apps/gor-api:/app
      - /app/venv
    working_dir: /app
    depends_on:
      qdrant:
        condition: service_healthy
    networks:
      - acp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Vector Database
  qdrant:
    image: qdrant/qdrant:latest
    container_name: acp-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    env_file:
      - ./apps/gor-api/.env
    networks:
      - acp-network
    healthcheck:
      test: ["CMD", "bash", "-c", "timeout 5 bash -c '</dev/tcp/localhost/6333' && echo 'Port 6333 is open' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # MCP Offers Server
  mcp-offers:
    build:
      context: ./apps/mcp-offers
      dockerfile: Dockerfile
    container_name: acp-mcp-offers
    ports:
      - "3002:3002"
    environment:
      - GOR_BASE_URL=http://gor-api:3001
      - MCP_HOST=0.0.0.0
      - MCP_PORT=3002
      - LOG_LEVEL=INFO
    depends_on:
      gor-api:
        condition: service_healthy
    networks:
      - acp-network
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; from mcp_offers.gor_client import GORClient; asyncio.run(GORClient('http://gor-api:3001').health_check())"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Consumer Agent CLI (interactive)
  consumer-agent-cli:
    build:
      context: ./apps/consumer-agent-cli
      dockerfile: Dockerfile
    environment:
      - MCP_HOST=mcp-offers
      - MCP_PORT=3002
      - GOR_BASE_URL=http://gor-api:3001
      - LOG_LEVEL=INFO
    depends_on:
      mcp-offers:
        condition: service_healthy
    networks:
      - acp-network
    stdin_open: true
    tty: true
    profiles:
      - cli

  # Transaction Simulator (placeholder for Day 5)
  tx-simulator:
    build:
      context: ./apps/tx-simulator
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
    networks:
      - acp-network
    profiles:
      - future

  # Restaurant Agents (placeholder for Day 4)
  restaurant-agent-otto:
    build:
      context: ./apps/restaurant-agents
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - AGENT_ID=otto_portland
      - PORT=4001
    networks:
      - acp-network
    profiles:
      - future

  restaurant-agent-street:
    build:
      context: ./apps/restaurant-agents
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - AGENT_ID=street_exeter
      - PORT=4002
    networks:
      - acp-network
    profiles:
      - future

  restaurant-agent-newicks:
    build:
      context: ./apps/restaurant-agents
      dockerfile: Dockerfile
    ports:
      - "4003:4003"
    environment:
      - AGENT_ID=newicks_lobster
      - PORT=4003
    networks:
      - acp-network
    profiles:
      - future

volumes:
  qdrant_data:

networks:
  acp-network:
    driver: bridge

# Development overrides
x-dev-overrides: &dev-overrides
  volumes:
    - ./apps:/app/apps:ro
    - ./data:/app/data
  environment:
    - LOG_LEVEL=DEBUG
    - PYTHONPATH=/app

# Production overrides
x-prod-overrides: &prod-overrides
  restart: unless-stopped
  environment:
    - LOG_LEVEL=INFO
